import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const dictPath = join(__dirname, "..", "dicts", "romaji_kanji.json");
const outPath = join(__dirname, "..", "src", "data.ts");

const raw = JSON.parse(readFileSync(dictPath, "utf-8"));

const entries = [];
const keys = Object.keys(raw).sort();

for (const romaji of keys) {
  const entry = raw[romaji];
  const kanji = (entry.kanji || []).map((k) => {
    if (typeof k === "string") return [k, []];
    return [k.char, k.meaning || []];
  });

  const row = [romaji, entry.hiragana || null, entry.katakana || null, kanji];
  entries.push(row);
}

const tsContent = `// Auto-generated by scripts/build-data.js — do not edit
// [romaji, hiragana | null, katakana | null, Array<[char, meanings[]]>]
export type DictEntry = [string, string | null, string | null, Array<[string, string[]]>];
export const dict: DictEntry[] = ${JSON.stringify(entries)};
`;

writeFileSync(outPath, tsContent, "utf-8");
console.log(`Generated ${entries.length} entries → ${outPath}`);
